import 'dart:math';
import 'package:cripto/models/Integrators_model.dart';

class MoedaRepository {
  static List<Integrators> tabela = [
    Integrators(
      name: 'Solarium Tech',
      address: 'Rua das Flores, 4956',
      city: 'Porto Alegre',
      zipcode: '16721-625',
      cnpj: '79.740.522/0001-93',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(11) 3456-7890',
      email: 'contato@solarbrilhante.com.br',
      isActive: true,
      observation:
          'O sistema solar foi instalado com 98% de eficiência na captação de energia',
    ),
    Integrators(
      name: 'EnerSun Integradores',
      address: 'Rua Augusta, 1914',
      city: 'Rio de Janeiro',
      zipcode: '51060-281',
      cnpj: '94.512.358/0001-40',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(21) 2345-6789',
      email: 'vendas@energialimpa.com.br',
      isActive: true,
      observation:
          'Manutenção preventiva realizada nas conexões elétricas, tudo dentro dos parâmetros',
    ),
    Integrators(
      name: 'BrightVolt Energia',
      address: 'Avenida Faria Lima, 8642',
      city: 'Rio de Janeiro',
      zipcode: '40805-144',
      cnpj: '47.108.417/0001-61',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(31) 8765-4321',
      email: 'suporte@solarenergytech.com.br',
      isActive: true,
      observation:
          'Painéis solares limpos em 12/02/2025, incremento de 5% na produção de energia',
    ),
    Integrators(
      name: 'Solaris Soluções',
      address: 'Avenida Ipiranga, 2101',
      city: 'Porto Alegre',
      zipcode: '83073-465',
      cnpj: '23.518.093/0001-71',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(41) 1234-5678',
      email: 'comercial@futurosolar.com.br',
      isActive: false,
      observation:
          'Conexão do inversor ao medidor de rede revisada, sem falhas detectadas',
    ),
    Integrators(
      name: 'EcoSun Engenharia',
      address: 'Avenida Paulista, 3998',
      city: 'Curitiba',
      zipcode: '14957-660',
      cnpj: '60.903.619/0001-32',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(51) 9876-5432',
      email: 'atendimento@raiosdesol.com.br',
      isActive: false,
      observation:
          'Recomendação de aumento da capacidade de armazenamento das baterias.',
    ),
    Integrators(
      name: 'Photon Power',
      address: 'Avenida Ipiranga, 4423',
      city: 'Brasília',
      zipcode: '47801-322',
      cnpj: '09.471.322/0001-88',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(12) 3456-7890',
      email: 'financeiro@energiasustentavel.com.br',
      isActive: true,
      observation:
          'Inversor apresentou sobrecarga em horários de pico, recomendação de upgrade.',
    ),
    Integrators(
      name: 'SolTech Renováveis',
      address: 'Avenida Faria Lima, 4539',
      city: 'Recife',
      zipcode: '27734-361',
      cnpj: '30.173.681/0001-70',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(22) 4567-8901',
      email: 'rh@solarnova.com.br',
      isActive: true,
      observation:
          'Configuração do sistema otimizada para melhor aproveitamento das horas de sol',
    ),
    Integrators(
      name: 'Verde Luz Sistemas',
      address: 'Rua Augusta, 6408',
      city: 'Brasília',
      zipcode: '69893-802',
      cnpj: '82.649.476/0001-20',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(32) 7654-3210',
      email: 'sac@luzsolar.com.br',
      isActive: false,
      observation:
          'Monitoramento remoto do sistema ativado, relatórios semanais enviados ao cliente.',
    ),
    Integrators(
      name: 'Helios Engenharia Solar',
      address: 'Avenida Faria Lima, 371',
      city: 'Recife',
      zipcode: '84608-4834',
      cnpj: '42.174.989/0001-37',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(42) 2345-6789',
      email: 'projetos@cleansolar.com.br',
      isActive: true,
      observation:
          'Falha intermitente na comunicação entre o inversor e o software de monitoramento',
    ),
    Integrators(
      name: 'Lumina Solar Solutions',
      address: 'Alameda Santos, 875',
      city: 'Belo Horizonte',
      zipcode: '69864-353',
      cnpj: '55.913.370/0001-58',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(52) 8765-4321',
      email: 'marketing@solpower.com.br',
      isActive: false,
      observation:
          'Instalação de painéis solares adicionais recomendada para aumentar a capacidade.',
    ),
    Integrators(
      name: 'SunVolt Serviços',
      address: 'Avenida Rio Branco, 2390',
      city: 'Curitiba',
      cnpj: '36.627.101/0001-09',
      zipcode: '83780-141',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(13) 1234-5678',
      email: 'diretor@energialimpatec.com.br',
      isActive: true,
      observation:
          'Teste de tensão realizado no sistema, dentro dos padrões de segurança',
    ),
    Integrators(
      name: 'BlueSky Energia',
      address: 'Rua 25 de Março, 1349',
      city: 'Belo Horizonte ',
      zipcode: '63414-901',
      cnpj: '26.392.745/0001-54',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '23) 9876-5432',
      email: 'orcamentos@soltech.com.br',
      isActive: false,
      observation:
          'Painéis solares orientados corretamente, sem necessidade de ajustes.',
    ),
    Integrators(
      name: 'SolarWay Integradores',
      address: 'Avenida Rio Branco, 6835',
      city: 'Fortaleza',
      zipcode: '67005-231',
      cnpj: '98.142.367/0001-10',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(33) 3456-7890',
      email: 'administracao@sunenergy.com.br',
      isActive: true,
      observation:
          'Eficiência do sistema solar caiu 3% devido ao acúmulo de sujeira nos painéis',
    ),
    Integrators(
      name: 'PowerGreen Engenharia',
      address: 'Alameda Santos, 581',
      city: 'Porto Alegre',
      zipcode: '58909-705',
      cnpj: '69.801.235/0001-29',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(43) 4567-8901',
      email: 'compras@solardynamics.com.br',
      isActive: false,
      observation:
          'inversor solar foi atualizado para o firmware mais recente, melhora no desempenho.',
    ),
    Integrators(
      name: 'SolSmart Soluções',
      address: 'Avenida Ipiranga, 899',
      city: 'Rio de Janeiro',
      zipcode: '85981-860',
      cnpj: '04.125.769/0001-44',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(53) 7654-3210',
      email: 'gerencia@ecosolar.com.br',
      isActive: true,
      observation:
          'Sistema de backup ativado com sucesso, garantindo energia durante interrupções',
    ),
    Integrators(
      name: 'EcoLight Energia',
      address: 'Rua 25 de Março, 9804',
      city: 'Porto Alegre',
      zipcode: '66552-899',
      cnpj: '85.671.292/0001-31',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(14) 2345-6789',
      email: 'atendimento@energiasolarplus.com.br',
      isActive: false,
      observation:
          'Baterias de lítio substituídas por novas com maior capacidade de armazenamento.',
    ),
    Integrators(
      name: 'Aurora Solar Experts',
      address: 'Avenida Rio Branco, 4523',
      city: 'Salvador',
      zipcode: '38437-955',
      cnpj: '77.301.812/0001-47',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(24) 8765-4321',
      email: 'comercial@solarmaster.com.br',
      isActive: true,
      observation:
          'Inversor está operando próximo ao limite de sua capacidade, monitoramento recomendado',
    ),
    Integrators(
      name: 'HelioVolt Instalações',
      address: 'Rua dos Andradas, 6901',
      city: 'Recife',
      zipcode: '57395-192',
      cnpj: '12.438.576/0001-95',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(34) 1234-5678',
      email: 'suporte@greenlightenergy.com.br',
      isActive: false,
      observation:
          'Redução de 10% na produção de energia durante o inverno, esperado para a região.',
    ),
    Integrators(
      name: 'SunFlow Energia',
      address: 'Avenida Rio Branco, 514 ',
      city: 'Belo Horizonte',
      zipcode: '86316-733',
      cnpj: '53.870.604/0001-6',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '44) 9876-5432',
      email: 'contato@energiasolarbrasil.com.br',
      isActive: true,
      observation:
          'Sistema integrado à rede elétrica com sucesso, venda de excedente de energia ativa.',
    ),
    Integrators(
      name: 'NovaEnergia Integradores',
      address: 'Rua dos Andradas, 3913',
      city: 'Brasília',
      zipcode: '15205-195',
      cnpj: '66.015.398/0001-11',
      icone: 'https://i.imgur.com/Nkoh9Ck.png',
      phone: '(54) 3456-7890',
      email: 'vendas@sunriseenergia.com.br',
      isActive: false,
      observation:
          'Relatório de desempenho enviado ao cliente, mostrando 20% de economia mensal na conta.',
    ),
  ];
}
